package configuration;

public class BusConfig {
	int BUS_MIN_WATING_ITERATIONS_AFTER_SEND = 10;
	int BUS_PING_OFFSET = 10;
	byte BUS_PING_FUNCTION = (byte) 0xFF;
	long BUS_TIMEWINDOW_VALIDITY_ITERATIONS_MAX = 200;
	byte FRAME_MIN_LEN = 7;
	byte FRAME_MAX_LEN = 50; 
	byte FRAME_PROCESSING_MIN_LEN = 51; 

	public BusConfig() {
		super();
	}

	public int getBUS_MIN_WATING_ITERATIONS_AFTER_SEND() {
		return BUS_MIN_WATING_ITERATIONS_AFTER_SEND;
	}

	public void setBUS_MIN_WATING_ITERATIONS_AFTER_SEND(int bUS_MIN_WATING_ITERATIONS_AFTER_SEND) {
		BUS_MIN_WATING_ITERATIONS_AFTER_SEND = bUS_MIN_WATING_ITERATIONS_AFTER_SEND;
	}

	public int getBUS_PING_OFFSET() {
		return BUS_PING_OFFSET;
	}

	public void setBUS_PING_OFFSET(int bUS_PING_OFFSET) {
		BUS_PING_OFFSET = bUS_PING_OFFSET;
	}

	public byte getBUS_PING_FUNCTION() {
		return BUS_PING_FUNCTION;
	}

	public void setBUS_PING_FUNCTION(byte bUS_PING_FUNCTION) {
		BUS_PING_FUNCTION = bUS_PING_FUNCTION;
	}

	public long getBUS_TIMEWINDOW_VALIDITY_ITERATIONS_MAX() {
		return BUS_TIMEWINDOW_VALIDITY_ITERATIONS_MAX;
	}

	public void setBUS_TIMEWINDOW_VALIDITY_ITERATIONS_MAX(long bUS_TIMEWINDOW_VALIDITY_ITERATIONS_MAX) {
		BUS_TIMEWINDOW_VALIDITY_ITERATIONS_MAX = bUS_TIMEWINDOW_VALIDITY_ITERATIONS_MAX;
	}

	public byte getFRAME_MIN_LEN() {
		return FRAME_MIN_LEN;
	}

	public void setFRAME_MIN_LEN(byte fRAME_MIN_LEN) {
		FRAME_MIN_LEN = fRAME_MIN_LEN;
	}

	public byte getFRAME_MAX_LEN() {
		return FRAME_MAX_LEN;
	}

	public void setFRAME_MAX_LEN(byte fRAME_MAX_LEN) {
		FRAME_MAX_LEN = fRAME_MAX_LEN;
	}


	public byte getFRAME_PROCESSING_MIN_LEN() {
		return FRAME_PROCESSING_MIN_LEN;
	}

	public void setFRAME_PROCESSING_MIN_LEN(byte fRAME_PROCESSING_MIN_LEN) {
		FRAME_PROCESSING_MIN_LEN = fRAME_PROCESSING_MIN_LEN;
	}
	
}